### ISSUE TITLE
Error on chrome extension

### ISSUE THREAD

**Issue by balajeek** [go-shiori/shiori-web-ext#18]
I am unable to use the chrome extension, install fine, when i click bookmark it shows the Login screen, I enter my service url, username, password and click login, i get the following error.

"json: cannot unmarshal bool into Go struct field .remember of type int"

FYI: i am able to access my shiori site directly and add bookmarks that way.

Please let me know. thanks.

**Comment by jajpater** [comment]
Same here

**Comment by CattopyTheWeb** [comment]
Same

**Comment by fmartingr** [comment]
What server/extension version are you using?

**Comment by CattopyTheWeb** [comment]
> What server/extension version are you using?

Extension: 1.1
Server: latest

**Comment by fmartingr** [comment]
> Extension: 1.1

Can you send a screenshot? There's no version 1.1 of the extension. (or should not be)

**Comment by CattopyTheWeb** [comment]
![image](https://github.com/go-shiori/shiori-web-ext/assets/115007754/749a7348-a714-4499-a534-3fa84d9e393c)
<img width="310" alt="image" src="https://github.com/go-shiori/shiori-web-ext/assets/115007754/7038848e-5b67-433e-8d02-5fab0eefbbc7">

**Comment by fmartingr** [comment]
That extension belong to [this repository](https://github.com/kozko2001/shiori-extension). Please fill your issue there.
