### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by wpuckering** [go-shiori/shiori-web-ext#3]
Would like to request a Chrome extension.

**Comment by vfauth** [comment]
If you download the source code, pack it using Chrome and install it from the resulting file, it will work fine.

**Comment by balajeek** [comment]
I am unable to use the chrome extension, install fine, when i click bookmark it shows the Login screen, I enter my service url, username, password and click login, i get the following error.

"json: cannot unmarshal bool into Go struct field .remember of type int"

FYI: i am able to access my shiori site directly and add bookmarks that way.

Please let me know. thanks.

**Comment by jcn50** [comment]
@balajeek the chrome extension is available here:
https://github.com/go-shiori/shiori-web-ext/releases/
the ZIP file shall be downloaded and unzipped to be installed in Chrome/Opera/Firefox (the Developer Mode needs to be activated).

I think this issue can be closed!

**Comment by fmartingr** [comment]
Thank you for pointing that out @jcn50.

I have put some basic instructions on how to download and run the extension under https://github.com/go-shiori/shiori-web-ext/discussions/52.

Keep in mind that the extension is still in beta tate, so right now there's no plans to release the extension to the chrome web store.
