### ISSUE TITLE
tags not added to Firefox

### ISSUE THREAD

**Issue by robotamer** [go-shiori/shiori-web-ext#33]
I like where this is going, thanks ...

Tags are added to Shiori, but not to Firefox bookmarks.

**Comment by fmartingr** [comment]
Hey @robotamer I don't understand the issue. Can you explain it in more detail?

**Comment by robotamer** [comment]
Well @fmartingr  when you post a links, you get to add tags/keywords in to an input field for that link/bookmark.
Those tags get saved to Shiori, however in firefox the bookmark gets added locally, but without the tags.
