### ISSUE TITLE
I cannot log into the Firefox addon for Shiori even thought the site (local IP) is correct and working fine.

### ISSUE THREAD

**Issue by cleverestx** [go-shiori/shiori-web-ext#70]
![image](https://github.com/go-shiori/shiori-web-ext/assets/28905253/52fd21af-a255-4334-a815-b1f333e7f9b5)

And

![image](https://github.com/go-shiori/shiori-web-ext/assets/28905253/9973fa53-9b45-4a58-a127-7431e2d30bc0)

I am using this in Docker, and YES the site works fine when accessing to normally, I can log in, add bookmarks, etc...

Help?

Thank you!

**Comment by kdorland** [comment]
I have the same issue. Downgraded to v0.8.7 and it worked. I'm also running the latest shiori docker image. I'm using the latest Firefox.

**Comment by cleverestx** [comment]
Thanks for the info. Hopefully this can be looked at....

**Comment by cleverestx** [comment]
Sadly I'm having the same issue w/ 0.8.7 as well :-(

I was able to log in fine with the latest version using a RP address, but I would like this to work via Local IP if possible...

**Comment by fmartingr** [comment]
Which version of Shiori are you using? The latest extension update changes the login endpoint to the new one on 1.6.0+. We have not made any other changes that I remember to restrict certain hostname validation or anything else, but a scheme is required.

**Comment by cleverestx** [comment]
> Which version of Shiori are you using? The latest extension update changes the login endpoint to the new one on 1.6.0+. We have not made any other changes that I remember to restrict certain hostname validation or anything else, but a scheme is required.

The latest version. It works only through my RP address. I get the 404 error above if I use my local IP address for Shiori instead (which loads fine if I access it in my browser) - let me know if you need anything else.

**Comment by ArnaudKunzi** [comment]
I had the same 404 error happening on a localhost endpoint, but in my case it was because I used an older version (0.8). Somehow, all Firefox Shiori add-ons on addons.mozilla.org are obsolete and uploaded by third parties. Installing the *.xpi file from the latest release did the trick.

**Comment by ArnaudKunzi** [comment]
I forgot to mention that alongside this I downgraded from the @latest branch to the 1.6.1 release

**Comment by kdorland** [comment]
I just did a docker pull to test with the latest image of shiori, using the latest extension  v1.6.0.1, and now it's working again. I'm even using a reverse proxy (caddy).

**Comment by ArnaudKunzi** [comment]
Which image did you use? I did not find one that was using a shiori version more recent than 1.6.0

**Comment by kdorland** [comment]
> Which image did you use? I did not find one on dockerhub that was using a shiori version more recent than 1.6.0rc6 (kennylouie/shiori)

I'm currently using this one which is the latest currently: 
https://github.com/go-shiori/shiori/pkgs/container/shiori/200904447?tag=v1.6.2

**Comment by cleverestx** [comment]
You guys had me hopeful for a moment.....I did get a NEW error with that later version installed, but still won't log in via local IP 
![image](https://github.com/go-shiori/shiori-web-ext/assets/28905253/218810a9-0bea-4cb1-9f4c-84ee98a88319)

This time is appeared to have wiped my other user account I had made when I logged into the default account and won't let me make the same accound claiming bad password, but it's not, I saved this one in bitlocker so I know it's valid. Sigh.

**Comment by cleverestx** [comment]
Never mind, it works now, had to create new account, log out, log back in, now it detects the IP host - YAY!

**Comment by super-qua** [comment]
I haven't tried it yet, but you should be able to install a xpi file on android by

- open settings
- go to about
- tap the Firefox logo 5 times
- back in the main settings "install add-on from file"

**Comment by janaxhell** [comment]
In my case, I'm using extension from Vivaldi and besides having to re-login at least once per day when I use it, it worked fine.
As of today (but maybe the entire month) I get **TypeError: Failed to fetch** when I try to login from Extensions Options page.
I have tried to reinstall from Unpacked, but nothing changed. When I click the bookmarklet, it behaves as if it worked fine, but nothing is actually grabbed to my server. I have tried on purpose on Firefox and I get **Error 404** when I try to login from bookmarlet. 
What I see in the logs is this:

```
time="2024-09-10T11:29:40Z" level=info msg="93.188.100.12 - 4b32b08dfc20 [10/Sep/2024:11:29:40 +0000] \"GET /bookmark/2735/thumb\" 200 42719 \"https://xxx.xxx.xxx/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36\" (4169ms)" clientIP=93.188.100.12 dataLength=42719 hostname=4b32b08dfc20 latency=4169 method=GET path=/bookmark/2735/thumb referer="https://xxx.xxx.xxx/" statusCode=200 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
time="2024-09-10T11:29:40Z" level=info msg="93.188.100.12 - 4b32b08dfc20 [10/Sep/2024:11:29:40 +0000] \"GET /bookmark/2734/thumb\" 200 80096 \"https://xxx.xxx.xxx/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36\" (4198ms)" clientIP=93.188.100.12 dataLength=80096 hostname=4b32b08dfc20 latency=4198 method=GET path=/bookmark/2734/thumb referer="https://xxx.xxx.xxx/" statusCode=200 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
time="2024-09-10T11:29:40Z" level=info msg="93.188.100.12 - 4b32b08dfc20 [10/Sep/2024:11:29:40 +0000] \"GET /bookmark/2732/thumb\" 200 90691 \"https://xxx.xxx.xxx/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36\" (4258ms)" clientIP=93.188.100.12 dataLength=90691 hostname=4b32b08dfc20 latency=4258 method=GET path=/bookmark/2732/thumb referer="https://xxx.xxx.xxx/" statusCode=200 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
time="2024-09-10T11:32:48Z" level=warning msg="93.188.100.12 - 4b32b08dfc20 [10/Sep/2024:11:32:48 +0000] \"POST /api/login\" 404 0 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0\" (1ms)" clientIP=93.188.100.12 dataLength=0 hostname=4b32b08dfc20 latency=1 method=POST path=/api/login referer= statusCode=404 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
time="2024-09-10T11:33:32Z" level=warning msg="93.188.100.12 - 4b32b08dfc20 [10/Sep/2024:11:33:32 +0000] \"POST /api/login\" 404 0 \"\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0\" (1ms)" clientIP=93.188.100.12 dataLength=0 hostname=4b32b08dfc20 latency=1 method=POST path=/api/login referer= statusCode=404 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
```

**Comment by fmartingr** [comment]
Closing this one in favor of #72. I have put [this comment](https://github.com/go-shiori/shiori-web-ext/issues/70#issuecomment-2101821474) in that issue to send people here.

As an statement of sorts, I'm not very familiar with the webextension framework and since this plugin is still labeled as "beta" and fairly limited I have not been paying it much attention. Any help in this area would be really appreciated. I have some ideas but it will take time to make them a reality.
